version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "angularjs",
    "meteor",
    "angular"
  ]
  environment = [
    "jquery",
    "nodejs",
    "cypress",
    "mongo",
    "browser",
    "jest",
    "mocha",
    "vitest",
    "jasmine"
  ]

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ansible"

[[transformers]]
name = "scalafmt"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "swift-format"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "dotnet-format"
